language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: Ii+zCSZjZf8Wue2hBSRmkNOdIj6YuShodoIyj6bKYinqZkpiu27Z16fBWxLheYybrtVB6uNWOnPq5fHpEpIn61xaOGR7esjJBRHoygNN0Bp9CRCUKTTaRte0lGjobJFTGh0tgN9n9igBHGgkoAKa9Q966iNw+ZovOYpErF0C2y2r1p7RgT5EkKF/Zr2adEI67qzHPIrheSTnBaUtMMl7i7NLs4grlGUqbfykHrYhd8VT4IfirYQtT1aYQYBHSdAvvBdwQo78ugle1SxnhatEncjWMgXOAHmWEb5O5VhnEPjYL177ac7upSm7yuYjaZVXhy399utDW24quw5OcEWJT+cc6KupERmcvQVpsnmP3tSjgi59SSkC+OKfe+1sPu2Legm79v0lw8VlFgI224GEfrTozFWJWd7pvBtwLYBLk3GJej8JGSTPzk8SZG5tzkdHXsA6hGecIA9M954NlbotDTOHdNAURgDT44v/+Gxk/RXRVOMCZteFYP+Fnfs153mx/2Fo3B6OzPXJVKk62yF6ypRkMIDaEWFjDLtelfMCflj2njZhsLufl6wWFThmAKoArYmq5yiLjbXEqRUh1XnK8oJuccEc5kU8Gd8UIAjyAti9VZVFkgpFqfcV4Ya0uCBuGcugrn6DY4u0dVXeVzZ7TlkKG3VI/EFcEPDhGVwKfVE=
  app: heartstrong
  on:
    repo: chang-steven/strong-heart-api
